# Generated by Django 4.1.1 on 2022-09-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profile_pic', models.ImageField(upload_to='')),
                ('age', models.IntegerField()),
                ('website', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
