# Generated by Django 4.1.1 on 2022-09-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmdport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_service_desc', models.TextField()),
                ('subtitle', models.CharField(max_length=100)),
                ('subtitle_desc', models.TextField()),
                ('photo_category', models.CharField(max_length=100)),
                ('photo_category_price', models.IntegerField()),
                ('reviews_desc', models.TextField()),
                ('reviewer_name', models.CharField(max_length=50)),
            ],
        ),
    ]
